Added more information to the firewall scripts.

diff --git a/bin/geoshape-firewall-disable b/bin/geoshape-firewall-disable
--- a/bin/geoshape-firewall-disable
+++ b/bin/geoshape-firewall-disable
@@ -1,6 +1,20 @@
 #!/bin/bash
 
+NOW=$(date +"%F")
+NOWT=$(date +"%T")
+BACKUP_FILE="/opt/rules-$NOW-$NOWT.conf"
+while true; do
+    read -p "Are you sure you want to disable the firewall and save the current configuration to $BACKUP_FILE? " yn
+    case $yn in
+        [Yy]* ) break;;
+        [Nn]* ) echo "    Aborting!";exit 1;;
+        * ) echo "    Please answer yes or no.";;
+    esac
+done
+
 IPTABLES="$(which iptables)"
+
+iptables-save > $BACKUP_FILE
 
 # RESET DEFAULT POLICIES
 $IPTABLES -P INPUT ACCEPT
@@ -19,3 +33,5 @@ $IPTABLES -t nat -F
 $IPTABLES -t nat -X
 $IPTABLES -t mangle -F
 $IPTABLES -t mangle -X
+
+echo "Firewall disabled."
